### ISSUE TITLE
Looking forward to seeing the code here :) 

### ISSUE THREAD

**Issue by doesselmannm360** [harsh19/SPINE#1]
Are you still planning to release the code? Thanks !

**Comment by harsh19** [comment]
Hi doesselmannm360, 
Thank you for showing interest in our work. We are in the process of cleaning up the codebase and adding some documentation. We will be releasing the code and resulting embeddings data in few weeks time.

**Comment by doesselmannm360** [comment]
Thank you!

**Comment by yya518** [comment]
Still planning to release the code?

**Comment by chijames** [comment]
Look forward to the code:)

**Comment by danishpruthi** [comment]
The code for the paper is available now. Apologies for the delay!
