### ISSUE TITLE
Need clarification on NP bracketing problem

### ISSUE THREAD

**Issue by svjan5** [harsh19/SPINE#3]
Hi, I have a few queries.
1. Generally, in ML, we take the larger part of data for training and smaller for testing. But [here](https://github.com/harsh19/SPINE/blob/master/code/evaluation/extrinsic_downstream/np_bracketing/get_data.py#L26) you are taking 9 splits for testing and only 1 split for training. Is it because of the nature of the problem or has been followed in the previous works? Please clarify. 

2. I also wanted to know whether it will be possible for you to share the code for evaluation on Sentiment Analysis task which has been used in the paper.

**Comment by harsh19** [comment]
1. For NP bracketing, we follow the same evaluation framework as in prior work 'Sparse Overcomplete Word Vector Representations. Faruqui et al. 2015' (Appendix B, 'NP bracketing (NP)'. http://www.aclweb.org/anthology/P15-1144 ). They had tuned on 1 split and reported results on the remaining 9 splits. 

2. We haven't yet ported the sentiment analysis evaluation to our new codebase.

**Comment by svjan5** [comment]
Thanks for the clarification. If possible please share the sentiment analysis code.
