### ISSUE TITLE
Update to newer Pytorch

### ISSUE THREAD

**Issue by impredicative** [harsh19/SPINE#5]
Is it possible to update this to use a newer Pytorch? Thanks.

**Comment by harsh19** [comment]
Hi,  Feel free to try with pytorch 0.3. As of now, we are not planning to update code for newer pytorch  versions.

**Comment by jacobdanovitch** [comment]
@harsh19 I've updated this to `torch==1.3.1`. Would you like me to make a PR? This allows it to run on CUDA on Tesla T4s like Colab uses, it's really fast.

**Comment by harsh19** [comment]
Thanks @jacobdanovitch  Maybe it's simpler for me to just add a link to your repository to the ReadMe file? Please let me know the repository url. Thank!

**Comment by jacobdanovitch** [comment]
> Thanks @jacobdanovitch Maybe it's simpler for me to just add a link to your repository to the ReadMe file? Please let me know the repository url. Thank!

I've forked the repo, the link is [here](https://github.com/jacobdanovitch/SPINE). I also sped up the visualization a bit with numpy and pandas. Not sure if it's fully stable right now but everything should be in working order for the most part.
