### ISSUE TITLE
add new loss term in loss function for a new idea

### ISSUE THREAD

**Issue by hangzhang23** [harsh19/SPINE#7]
Hi, we are studying your thesis these days, and we have an idea to implement a local loss function by adding a term in the original loss function.  I explain our idea, and if you have insterest you could judge it's possibility.

before every batch, we use knn approach to find the _k_ nearlist words of every input, after one batch training we get a embedding space and for this input we could also use knn to find _k_ nearlist words, then we find out _m_ words (0<=_m_<=_k_)  are the same after embedding. we add this item in original loss function and minimize it we could get sparse interpretable embeddings that has the porperties of word2vec(predict word in sentence). is that possible?

> 
(sorry I can't implement a latex formula in issue, but if you have interest you could copy the latex code and have a look)
https://latex.codecogs.com/gif.latex?[\frac{1}{\left | D \right |}\sum \left ( \frac{k-\left ( U_{I}\bigcap U_{o} \right )}{k} \right )]

like the term above, the https://latex.codecogs.com/gif.latex?[U_{I}] is the k-nearlist word list before embedding, and the  https://latex.codecogs.com/gif.latex?[U_{o}] is the k-nearlist word list of one word in embedding space.

**Comment by harsh19** [comment]
Hi,
Thanks for showing interest in our work.
Sure, sounds like a reasonable thing to try.  Feel free to fork/clone our repo and try this out.
However, since this issue is more like an additional feature request rather than an issue with code for our paper, we are closing this for now.
